name: funkyabx

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
      - '4001:4001'
    volumes:
      - ./:/app/funkyabx
    working_dir: /app/funkyabx
    depends_on:
      - database
    environment:
      MIX_ENV: dev
      DATABASE_URL: database

  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-funkyabx_dev}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-funkyabx_dev}", "-U", "${POSTGRES_USER:-postgres}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
#      - ./sql:/var/tmp/sql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:

  database_data:

